In [2]:
import pandas as pd
import os
from pathlib import Path

In [32]:
price_d1 = pd.read_csv(Path("data") / "prices_round_0_day_-1.csv", sep=";")
price_d1[price_d1["product"] == "EMERALDS"]

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
1,-1,0,EMERALDS,9992,14,9990,29,NaN,NaN,10008,14,10010,29,NaN,NaN,10000.0,0.0
2,-1,100,EMERALDS,9992,11,9990,22,NaN,NaN,10008,11,10010,22,NaN,NaN,10000.0,0.0
4,-1,200,EMERALDS,9992,15,9990,20,NaN,NaN,10008,15,10010,20,NaN,NaN,10000.0,0.0
7,-1,300,EMERALDS,9992,11,9990,29,NaN,NaN,10008,11,10010,29,NaN,NaN,10000.0,0.0
9,-1,400,EMERALDS,9992,12,9990,25,NaN,NaN,10008,12,10010,25,NaN,NaN,10000.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19991,-1,999500,EMERALDS,9992,14,9990,29,NaN,NaN,10008,14,10010,29,NaN,NaN,10000.0,0.0
19992,-1,999600,EMERALDS,9992,14,9990,28,NaN,NaN,10008,14,10010,28,NaN,NaN,10000.0,0.0
19995,-1,999700,EMERALDS,9992,12,9990,26,NaN,NaN,10008,12,10010,26,NaN,NaN,10000.0,0.0
19996,-1,999800,EMERALDS,9992,13,9990,20,NaN,NaN,10008,13,10010,20,NaN,NaN,10000.0,0.0
19999,-1,999900,EMERALDS,9992,10,9990,29,NaN,NaN,10008,10,10010,29,NaN,NaN,10000.0,0.0

In [23]:
price_d1 = pd.read_csv("prices_round_0_day_-2.csv", sep=";")
price_d1.head()

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
0,-2,0,EMERALDS,9992,11,9990,25,NaN,NaN,10008,11,10010,25,NaN,NaN,10000.0,0.0
1,-2,0,TOMATOES,4993,7,4992,17,NaN,NaN,5007,7,5008,17,NaN,NaN,5000.0,0.0
2,-2,100,TOMATOES,4998,5,4993,7,4992.0,16.0,5007,7,5008,16,NaN,NaN,5002.5,0.0
3,-2,100,EMERALDS,9992,15,9990,20,NaN,NaN,10008,15,10010,20,NaN,NaN,10000.0,0.0
4,-2,200,TOMATOES,4994,6,4993,20,NaN,NaN,5008,6,5009,20,NaN,NaN,5001.0,0.0

In [27]:
trade_d1 = pd.read_csv("trades_round_0_day_-1.csv", sep=";")
trade_d1.head()

   timestamp  buyer  seller    symbol currency   price  quantity
0       3200    NaN     NaN  EMERALDS   XIRECS  9992.0         8
1       3400    NaN     NaN  TOMATOES   XIRECS  5009.0         2
2       5000    NaN     NaN  EMERALDS   XIRECS  9992.0         7
3       7000    NaN     NaN  TOMATOES   XIRECS  5010.0         4
4       9600    NaN     NaN  TOMATOES   XIRECS  4999.0         5

In [28]:
trade_d2 = pd.read_csv("trades_round_0_day_-2.csv", sep=";")
trade_d2.head()

   timestamp  buyer  seller    symbol currency    price  quantity
0        900    NaN     NaN  TOMATOES   XIRECS   5008.0         2
1       1700    NaN     NaN  TOMATOES   XIRECS   5006.0         3
2       4000    NaN     NaN  EMERALDS   XIRECS  10008.0         7
3       4100    NaN     NaN  TOMATOES   XIRECS   5002.0         3
4       5200    NaN     NaN  EMERALDS   XIRECS   9992.0         5